version: '3.8'
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
  scraper:
    build: .
    depends_on:
      - rabbitmq
  processor:
    build: .
    command: ["python", "processor.py"]
    depends_on:
      - rabbitmq
